Log:
  Encoding: plain
  TimeFormat: 2006-01-02 15:04:05
  Level: debug
  Stat: false

MsgForwarder:
  Brokers:
    - 10.0.0.5:9092
  Topic: "messages"

MsgSender:
  Brokers:
    - 10.0.0.5:9092
  Topic: "init_topic"

MsgDBSaver:
  Brokers:
    - 10.0.0.5:9092
  Topic: "msg_to_db"

RedisConf:
  Host: "10.0.0.3:6379"
  Type: "node"

MongoConf:
  Host: "10.0.0.6:27017"

MySQL:
  DataSource: root:123456@tcp(10.0.0.2:3306)/im_server_db?charset=utf8mb4&parseTime=True&loc=Local


WorkID: 1 # 雪花漂移id生成用
