Name: websocket-server
Host: 0.0.0.0
Port: 8082

Log:
  Encoding: plain
  TimeFormat: 2006-01-02 15:04:05
  Level: debug
  Stat: false

Auth:
  AccessSecret: wcnm123
  AccessExpire: 1440  # 单位为分钟


AuthRpc:
  Etcd:
    Hosts:
      - 10.0.0.4:2379
    Key: authrpc.rpc

MsgForwarder:
  Brokers:
    - 10.0.0.5:9092
  Topic: "messages"

WorkID: 1

MsgSender:
  Brokers:
    - 10.0.0.5:9092
  Topic: "websocket-server-1" # 最后一位为WorkID

RedisConf:
  Host: 10.0.0.3:6379
  Type: "node"

Etcd:
  Hosts:
    - 10.0.0.4:2379