// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: group.proto

package server

import (
	"context"

	"github.com/n8sPxD/cowIM/internal/business/group/rpc/internal/logic"
	"github.com/n8sPxD/cowIM/internal/business/group/rpc/internal/svc"
	"github.com/n8sPxD/cowIM/internal/business/group/rpc/types/groupRpc"
)

type GroupServer struct {
	svcCtx *svc.ServiceContext
	groupRpc.UnimplementedGroupServer
}

func NewGroupServer(svcCtx *svc.ServiceContext) *GroupServer {
	return &GroupServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupServer) GetGroupMembers(ctx context.Context, in *groupRpc.GroupMembersRequest) (*groupRpc.GroupMembersResponse, error) {
	l := logic.NewGetGroupMembersLogic(ctx, s.svcCtx)
	return l.GetGroupMembers(in)
}
