// Code generated by goctl. DO NOT EDIT.
package types

type AddFriendRequest struct {
	UserID   uint32 `json:"UserID"`
	FriendID uint32 `json:"friendId"`
}

type AddFriendResponse struct {
}

type GetFriendsRequest struct {
	UserID uint32 `json:"UserID"`
}

type GetFriendsResponse struct {
}
