// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	ID       uint32 `json:"id"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	ID uint32 `json:"id"`
}
