// Code generated by goctl. DO NOT EDIT.
// Source: authrpc.proto

package server

import (
	"context"

	"github.com/n8sPxD/cowIM/microservices/auth/rpc/internal/logic"
	"github.com/n8sPxD/cowIM/microservices/auth/rpc/internal/svc"
	"github.com/n8sPxD/cowIM/microservices/auth/rpc/types/authRpc"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	authRpc.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServer) UserConnStatus(ctx context.Context, in *authRpc.ConnRequest) (*authRpc.Empty, error) {
	l := logic.NewUserConnStatusLogic(ctx, s.svcCtx)
	return l.UserConnStatus(in)
}
