// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/n8sPxD/cowIM/internal/apis/group/api/internal/svc"
	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/group",
				Handler: groupCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/group",
				Handler: groupInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/invite",
				Handler: groupInviteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/groups",
				Handler: groupJoinedHandler(serverCtx),
			},
		},
	)
}
