// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: group.proto

package group

import (
	"context"

	"github.com/n8sPxD/cowIM/internal/business/group/rpc/types/group"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GroupMembersRequest  = groupRpc.GroupMembersRequest
	GroupMembersResponse = groupRpc.GroupMembersResponse

	Group interface {
		GetGroupMembers(ctx context.Context, in *GroupMembersRequest, opts ...grpc.CallOption) (*GroupMembersResponse, error)
	}

	defaultGroup struct {
		cli zrpc.Client
	}
)

func NewGroup(cli zrpc.Client) Group {
	return &defaultGroup{
		cli: cli,
	}
}

func (m *defaultGroup) GetGroupMembers(ctx context.Context, in *GroupMembersRequest, opts ...grpc.CallOption) (*GroupMembersResponse, error) {
	client := groupRpc.NewGroupClient(m.cli.Conn())
	return client.GetGroupMembers(ctx, in, opts...)
}
