// Code generated by goctl. DO NOT EDIT.
package types

type AddFriendRequest struct {
	UserID   uint32 `header:"UserID"`
	FriendID uint32 `json:"friendId"`
}

type AddFriendResponse struct {
}

type FriendInfo struct {
	FriendID uint32 `json:"friendId"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type GetFriendsRequest struct {
	UserID uint32 `header:"UserID"`
}

type GetFriendsResponse struct {
	Friends []FriendInfo `json:"friends"`
}
