name: 搭建前端

on:
  push:
    paths:
      - 'web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: frontend
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: 目录打包
        run: |
          tar -czf web.tar.gz -C web .

      - name: 上传web到服务器
        uses: moonpathbg/scp_uploader@latest
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./web.tar.gz"
          target: "/home/www/cowim"

      - name: 部署webserver
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            mkdir -p /home/www/cowim
            cd /home/www/cowim
            tar -xzf web.tar.gz -C .
            rm web.tar.gz
            echo "${{ secrets.SUDO_PASSWD }}" | sudo -S openresty -s reload

      - name: 清理本地文件
        run: |
          rm -f web.tar.gz