name: group-restful-docker-build
on:
  push:
    paths:
      - .github/workflows/group-restful-docker-build.yml
      - internal/apis/group/api/**

jobs:
  base-rebuild-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: 登陆DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 重新构建base镜像，并push到DockerHub
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: n8spxd/cow-im:base


  build-and-push:
    runs-on: ubuntu-latest
    needs: base-rebuild-and-push
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: 登陆DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 构建group-api Docker镜像并push到DockerHub
        uses: docker/build-push-action@v6.9.0
        with:
          context: internal/apis/group/api
          push: true
          tags: n8spxd/cow-im:group-api